import type { NextPage } from 'next'
import Head from 'next/head'
import Header from '../components/header/Header'
import Container from '../components/container/Container'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Design System Starter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-black flex items-center justify-center h-screen">
        <Container className="text-center py-12">
          <h1 className="text-white text-5xl mb-3">
            Design System Starter Build
          </h1>
          <p className="text-gray-400">
            Multi-Branded Design System, using Style Dictionary, Tailwind CSS
            and Next.js.
          </p>
        </Container>
      </main>
    </div>
  )
}

export default Home
