import type { NextPage } from 'next'
import Head from 'next/head'
import Footer from '../components/footer/Footer'
import Header from '../components/header/Header'
import Container from '../components/container/Container'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Design System Starter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header className="mb-5">
        <Container className="text-center py-12">
          <h1 className="text-5xl mb-3">Design System Starter Kit</h1>
          <p className="text-gray-500">
            Get started building your own design system today.
          </p>
        </Container>
      </Header>
      <main>
        <Container>
          <div className="sm:grid sm:grid-cols-3 sm:gap-4 space-y-3 sm:space-y-0 mb-5">
            <div className="flex-col text-center items-center">
              <svg
                className="w-28 h-28 m-auto mb-5"
                fill="none"
                stroke="currentColor"
                viewBox="0 0 24 24"
                xmlns="http://www.w3.org/2000/svg"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M4 7v10c0 2.21 3.582 4 8 4s8-1.79 8-4V7M4 7c0 2.21 3.582 4 8 4s8-1.79 8-4M4 7c0-2.21 3.582-4 8-4s8 1.79 8 4m0 5c0 2.21-3.582 4-8 4s-8-1.79-8-4"
                />
              </svg>
              <h2 className="mb-3">Design Tokens</h2>
              <p>Style Dictionary manages your design tokens</p>
            </div>
            <div className="flex-col text-center items-center">
              <svg
                className="w-28 h-28 m-auto mb-5"
                fill="none"
                stroke="currentColor"
                viewBox="0 0 24 24"
                xmlns="http://www.w3.org/2000/svg"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4"
                />
              </svg>
              <h2 className="mb-3">Production Ready</h2>
              <p>Built using Next.js and Tailwind CSS</p>
            </div>
            <div className="flex-col text-center items-center">
              <svg
                className="w-28 h-28 m-auto mb-5"
                fill="none"
                stroke="currentColor"
                viewBox="0 0 24 24"
                xmlns="http://www.w3.org/2000/svg"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M20 7l-8-4-8 4m16 0l-8 4m8-4v10l-8 4m0-10L4 7m8 4v10M4 7v10l8 4"
                />
              </svg>
              <h2 className="mb-3">TypeScript</h2>
              <p>Components are TypeScript compatible</p>
            </div>
          </div>
        </Container>
      </main>
      <Footer className="text-center py-8">
        <Container>
          <p className="text-gray-500">Built by Nathan Edwards</p>
        </Container>
      </Footer>
    </div>
  )
}

export default Home
